### ISSUE TITLE
about the new book

### ISSUE THREAD

**Issue by wangcanqiang** [BruceEckel/OnJava8-Examples#24]
Hi, does the new book on java 8 has been published?

**Comment by BruceEckel** [comment]
The beta version is ready, which means the book is more-or-less complete but I expect various fixes to arise before deciding it is truly complete.

I have decided to publish exclusively through Google Play Books, which has an excellent reader on all platforms as well as what looks like true security, and this is something I'd like to try (especially since I am not trying to produce any side-effects from this book; my only goal is to sell the book and not produce consulting or training opportunities). The beta will appear for sale there first, for those who want it right now and are willing to tolerate whatever small errors might still exist. Once the book is polished, the beta users will be automatically updated to the finished book.

Unfortunately Google Play Books has not been accepting new publishers for some time now, however all the (scant) information from Google says this will happen "real soon now." I am trying to get help from contacts within Google, but so far with no luck. If anyone works for Google or has any connections there which might help it would be greatly appreciated.

**Comment by BruceEckel** [comment]
I've been able to work around the Google Books issue; the beta is now for sale at www.OnJava8.com and I'm on the cusp of moving it from beta to normal sales. You'll automatically get updates.

**Comment by andynrkri** [comment]
And?

**Comment by BruceEckel** [comment]
Yes: www.OnJava8.com

-- Bruce Eckel
MindViewLLC.com
B <http://blog.bruceeckel.com/>log: BruceEckel.com
SoftwareArchitectureForum.com <http://www.SoftwareArchitectureForum.com>
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicScala.com
Reinventing-Business.com <http://www.Reinventing-Business.com>
